### ISSUE TITLE
color logging fails with colorlog 2.6.0

### ISSUE THREAD

**Issue by gatufo** [scrapinghub/frontera#29]
```
File "/Library/Python/2.7/site-packages/crawl_frontier-0.2.0.post.dev7.pre-py2.7.egg/crawlfrontier/logger/formatters/color.py", line 14, in __init__
        reset=reset, style=style)
    exceptions.TypeError: __init__() got an unexpected keyword argument ‘format’
```

works with 2.4.0

**Comment by sibiryakov** [comment]
was fixed in https://github.com/scrapinghub/frontera/pull/91
